events { }
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen ${PORT}; # Nginx will listen on the port passed by the shell script
        root   /usr/share/nginx/html;
        index  index.html;
    }
}
